Vagrant.configure("2") do |config|

  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.network "private_network", ip: "192.168.0.100", virtualbox__intnet: true

  config.vm.provider 'virtualbox' do |virtualbox|
    virtualbox.customize ["modifyvm", :id, "--memory", 512]
  end

  # config.vm.provision :shell, inline: 'apt-get update -y --fix-missing'
  # config.vm.provision 'puppet' do |puppet|
  #    puppet.manifests_path = 'puppet/manifests'
  #    puppet.manifest_file  = 'site.pp'
  #    puppet.module_path = 'puppet/modules'
  #    puppet.options = '--verbose --debug'
  # end

end